# Generated by Django 3.2.8 on 2022-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Cuerpo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='Fecha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='NombreDeAutor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='Titulo',
            field=models.CharField(max_length=200),
        ),
    ]
